language: java
jdk:
    - oraclejdk8

install:
    - ./gradlew xjc assemble --info

script:
    - ./gradlew check --info

after_success:
    - ./gradlew test jacocoTestReport coveralls --info
