#!/bin/bash
if [[ "$1" == "" ]]; then
    echo "Usage: generateJavadoc <srcpath>"
    exit
fi

javadoc -encoding utf8 -docencoding utf8 -d . -sourcepath "$1" -exclude reiseplugin.data.helden.entities.jaxb -subpackages reiseplugin
